name: Update_front-end

on:
  push:
    paths:
      - 'Front-end/**'

jobs:
  Delete-S3:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Recupere repo
        uses: actions/checkout@v4
      - name: Connection AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{secrets.Full_S3_cloud_Resume_Challenge_role}}
          role-session-name: Zeeward
          aws-region: us-east-1
      - name: vider le Bucket
        run: 
          aws s3 rm s3://www.zeeward41.com --recursive
      - name: Upload new file
        run: 
          aws s3 cp Front-end s3://www.zeeward41.com --recursive
      - name: Invalidation CloudFront
        run:
          aws cloudfront create-invalidation --distribution-id ${{secrets.distribution_id}} --paths "/*"
          
